---
- hosts: masters[0]
  #connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - role: kubevirt

- hosts: masters[0]
  environment:
    http_proxy: ""
  roles:
    - role: "cdi"
